name: Deploy to Server

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install
        # or for Gradle
        # run: ./gradlew build

        # Deploy to First Server
      - name: Set up SSH for First Server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Shutdown application on First Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            pkill -f 'java -jar service-client-0.0.1-SNAPSHOT.jar' || true
          EOF

      - name: Create directory on the remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            mkdir -p /usr/bot
          EOF

      - name: Copy files via SSH
        run: scp -v -o StrictHostKeyChecking=no service-client/target/service-client-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/usr/bot/service-client-0.0.1-SNAPSHOT.jar

      - name: Execute SSH command on First Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            export POSTGRES_JDBC_URL=${{ secrets.POSTGRES_JDBC_URL }}
            export POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export S3_PUBLIC_URL=${{ secrets.S3_PUBLIC_URL }}
            export S3_PRIVATE_URL=${{ secrets.S3_PRIVATE_URL }}
            export S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
            export S3_PRIVATE_KEY=${{ secrets.S3_PRIVATE_KEY }}
            export S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            export BOT_NAME=${{ secrets.BOT_NAME }}
            export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            cd /usr/bot
            nohup java -jar service-client-0.0.1-SNAPSHOT.jar > bot.log 2>&1 &
          EOF

      # Deploy to Second Server
      - name: Set up SSH for Second Server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY_2 }}

      - name: Shutdown application on Second Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_2 }}@${{ secrets.SERVER_HOST_2 }} << 'EOF'
            pkill -f 'java -jar service-client-0.0.1-SNAPSHOT.jar' || true
          EOF

      - name: Create directory on the remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_2 }}@${{ secrets.SERVER_HOST_2 }} << 'EOF'
            mkdir -p /usr/bot
          EOF

      - name: Copy files via SSH
        run: scp -v -o StrictHostKeyChecking=no service-client/target/service-client-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USER_2 }}@${{ secrets.SERVER_HOST_2 }}:/usr/bot/service-client-0.0.1-SNAPSHOT.jar

      - name: Execute SSH command on Second Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_2 }}@${{ secrets.SERVER_HOST_2 }} << 'EOF'
            export POSTGRES_JDBC_URL=${{ secrets.POSTGRES_JDBC_URL_2 }}
            export POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME_2 }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_2 }}
            export S3_PUBLIC_URL=${{ secrets.S3_PUBLIC_URL_2 }}
            export S3_PRIVATE_URL=${{ secrets.S3_PRIVATE_URL_2 }}
            export S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY_2 }}
            export S3_PRIVATE_KEY=${{ secrets.S3_PRIVATE_KEY_2 }}
            export S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME_2 }}
            export BOT_NAME=${{ secrets.BOT_NAME_2 }}
            export BOT_TOKEN=${{ secrets.BOT_TOKEN_2 }}
            cd /usr/bot
            nohup java -jar service-client-0.0.1-SNAPSHOT.jar > bot.log 2>&1 &
          EOF
